<a href="https://colab.research.google.com/github/LuisPerdomo123/MachineLearning/blob/main/1_Introducci%C3%B3n_a_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a NumPy

Numpy es una librería fundamental para la computación científica con Python.



*   Proporciona arrays N-dimensionales
*   Implementa funciones matemáticas sofisticadas
*   Proporciona herramientas para integrar C/C++ y Fortran
*   Proporciona mecanismos para facilitar la realización de tareas relacionadas con álgebra lineal o números aleatorios.



## Imports

In [1]:
import numpy as np

## Arrays

Un **arrary** es una estructura de datos que consiste en una colección de elementos (valores o variables), cada uno identificado por al menos un indice o clave. Un array se almacena de modo que la posición de cada elemento se pueda calcular a partir de su tupla de indice mediante una fórmiula matemática. El tipo más simple de array es un array lineal, también llamado array unidimensional.

En numpy:


*   Cada dimensión se denomina **axis**
*   El número de dimensiones se denomina **rank**
*   La lista de dimensiones con su correspondiente longitud se denimina **shape**
*   El número total de elementos (multiplicación de la longitud de las dimensiones) se denomina **size**

In [4]:
# Array cuyos valores son todos
a = np.zeros((2, 4)) # Tiene dos filas y cuatro columnas

In [5]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**a** es un array:

*   Con dos **axis**, el primero de longitud 2 y el segundo de longitud 4.
*   Con un **rank** igual a 2.
*   Con un **shape** igual (2, 4)
*   Con un **size** igual a 8



In [6]:
a.shape

(2, 4)

In [7]:
a.ndim

2

In [8]:
a.size

8

## Creación de Arrays

In [10]:
# Array cuyos valores son todos 0
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
# Array cuyos valores son todos 1
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
# Array cuyos valores son todos el valor indicado como segundo parámetro de la función
